[package]
name = "gff"
version = "0.1.0"
authors = ["Hugo Camboulive <hugo@camboulive.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
nom = "5.1.2"
num_enum = "0.5.0"